//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogheApp.embedded {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BogheApp.embedded.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 呼叫 的本地化字符串。
        /// </summary>
        public static string AV_ButtonCall {
            get {
                return ResourceManager.GetString("AV_ButtonCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挂机 的本地化字符串。
        /// </summary>
        public static string AV_ButtonEndCall {
            get {
                return ResourceManager.GetString("AV_ButtonEndCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送文本 的本地化字符串。
        /// </summary>
        public static string AV_ButtonSendText {
            get {
                return ResourceManager.GetString("AV_ButtonSendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add video 的本地化字符串。
        /// </summary>
        public static string AV_MenuAddVideo {
            get {
                return ResourceManager.GetString("AV_MenuAddVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼叫 的本地化字符串。
        /// </summary>
        public static string AV_MenuCall {
            get {
                return ResourceManager.GetString("AV_MenuCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容共享 的本地化字符串。
        /// </summary>
        public static string AV_MenuContentSharing {
            get {
                return ResourceManager.GetString("AV_MenuContentSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挂机 的本地化字符串。
        /// </summary>
        public static string AV_MenuHangUp {
            get {
                return ResourceManager.GetString("AV_MenuHangUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保持通话 的本地化字符串。
        /// </summary>
        public static string AV_MenuHoldCall {
            get {
                return ResourceManager.GetString("AV_MenuHoldCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语音电话 的本地化字符串。
        /// </summary>
        public static string AV_MenuMakeAudioCall {
            get {
                return ResourceManager.GetString("AV_MenuMakeAudioCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼叫转移 的本地化字符串。
        /// </summary>
        public static string AV_MenuMakeTransfer {
            get {
                return ResourceManager.GetString("AV_MenuMakeTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频电话 的本地化字符串。
        /// </summary>
        public static string AV_MenuMakeVideoCall {
            get {
                return ResourceManager.GetString("AV_MenuMakeVideoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove video 的本地化字符串。
        /// </summary>
        public static string AV_MenuRemoveVideo {
            get {
                return ResourceManager.GetString("AV_MenuRemoveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送文件 的本地化字符串。
        /// </summary>
        public static string AV_MenuSendFile {
            get {
                return ResourceManager.GetString("AV_MenuSendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共享图片 的本地化字符串。
        /// </summary>
        public static string AV_MenuShareImage {
            get {
                return ResourceManager.GetString("AV_MenuShareImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共享视频 的本地化字符串。
        /// </summary>
        public static string AV_MenuShareVideo {
            get {
                return ResourceManager.GetString("AV_MenuShareVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Button_SignIn {
            get {
                return ResourceManager.GetString("Button_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称*: 的本地化字符串。
        /// </summary>
        public static string ContactEdit_DisplayName {
            get {
                return ResourceManager.GetString("ContactEdit_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组名称*: 的本地化字符串。
        /// </summary>
        public static string ContactEdit_Group {
            get {
                return ResourceManager.GetString("ContactEdit_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话号码*: 的本地化字符串。
        /// </summary>
        public static string ContactEdit_URI {
            get {
                return ResourceManager.GetString("ContactEdit_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称*: 的本地化字符串。
        /// </summary>
        public static string GroupEdit_DisplayName {
            get {
                return ResourceManager.GetString("GroupEdit_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string IM_Abort {
            get {
                return ResourceManager.GetString("IM_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邀请 的本地化字符串。
        /// </summary>
        public static string IM_Invite {
            get {
                return ResourceManager.GetString("IM_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语音电话 的本地化字符串。
        /// </summary>
        public static string IM_MakeAudioCall {
            get {
                return ResourceManager.GetString("IM_MakeAudioCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频电话 的本地化字符串。
        /// </summary>
        public static string IM_MakeVideoCall {
            get {
                return ResourceManager.GetString("IM_MakeVideoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项(...) 的本地化字符串。
        /// </summary>
        public static string IM_MenuOptions {
            get {
                return ResourceManager.GetString("IM_MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送文件 的本地化字符串。
        /// </summary>
        public static string IM_SendFile {
            get {
                return ResourceManager.GetString("IM_SendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送... 的本地化字符串。
        /// </summary>
        public static string IM_Sending {
            get {
                return ResourceManager.GetString("IM_Sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送消息 的本地化字符串。
        /// </summary>
        public static string IM_SendText {
            get {
                return ResourceManager.GetString("IM_SendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共享图片 的本地化字符串。
        /// </summary>
        public static string IM_ShareImage {
            get {
                return ResourceManager.GetString("IM_ShareImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共享视频 的本地化字符串。
        /// </summary>
        public static string IM_ShareVideo {
            get {
                return ResourceManager.GetString("IM_ShareVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string MainWindow_About {
            get {
                return ResourceManager.GetString("MainWindow_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加联系人 的本地化字符串。
        /// </summary>
        public static string MainWindow_AddContact {
            get {
                return ResourceManager.GetString("MainWindow_AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加分组 的本地化字符串。
        /// </summary>
        public static string MainWindow_AddGroup {
            get {
                return ResourceManager.GetString("MainWindow_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授权(0) 的本地化字符串。
        /// </summary>
        public static string MainWindow_Authorizations {
            get {
                return ResourceManager.GetString("MainWindow_Authorizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Boghe&apos;s Website 的本地化字符串。
        /// </summary>
        public static string MainWindow_BogheWebsite {
            get {
                return ResourceManager.GetString("MainWindow_BogheWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string MainWindow_ButtonCancel {
            get {
                return ResourceManager.GetString("MainWindow_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测更新 的本地化字符串。
        /// </summary>
        public static string MainWindow_CheckForUpdates {
            get {
                return ResourceManager.GetString("MainWindow_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所有事件 的本地化字符串。
        /// </summary>
        public static string MainWindow_DeleteAllEvents {
            get {
                return ResourceManager.GetString("MainWindow_DeleteAllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除联系人 的本地化字符串。
        /// </summary>
        public static string MainWindow_DeleteContact {
            get {
                return ResourceManager.GetString("MainWindow_DeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除分组 的本地化字符串。
        /// </summary>
        public static string MainWindow_DeleteGroup {
            get {
                return ResourceManager.GetString("MainWindow_DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Doubango&apos;s Website 的本地化字符串。
        /// </summary>
        public static string MainWindow_DoubangoWebsite {
            get {
                return ResourceManager.GetString("MainWindow_DoubangoWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑联系人 的本地化字符串。
        /// </summary>
        public static string MainWindow_EditContact {
            get {
                return ResourceManager.GetString("MainWindow_EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑分组 的本地化字符串。
        /// </summary>
        public static string MainWindow_EditGroup {
            get {
                return ResourceManager.GetString("MainWindow_EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string MainWindow_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Getting Started 的本地化字符串。
        /// </summary>
        public static string MainWindow_GettingStarted {
            get {
                return ResourceManager.GetString("MainWindow_GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Issue Tracker 的本地化字符串。
        /// </summary>
        public static string MainWindow_IssueTracker {
            get {
                return ResourceManager.GetString("MainWindow_IssueTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址薄 的本地化字符串。
        /// </summary>
        public static string MainWindow_MenuAddressBook {
            get {
                return ResourceManager.GetString("MainWindow_MenuAddressBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string MainWindow_MenuFile {
            get {
                return ResourceManager.GetString("MainWindow_MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史记录 的本地化字符串。
        /// </summary>
        public static string MainWindow_MenuHistory {
            get {
                return ResourceManager.GetString("MainWindow_MenuHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        public static string MainWindow_MenuTools {
            get {
                return ResourceManager.GetString("MainWindow_MenuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你没有消息 的本地化字符串。
        /// </summary>
        public static string MainWindow_NoMessages {
            get {
                return ResourceManager.GetString("MainWindow_NoMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string MainWindow_Options {
            get {
                return ResourceManager.GetString("MainWindow_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string MainWindow_Refresh {
            get {
                return ResourceManager.GetString("MainWindow_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        public static string MainWindow_Registrations {
            get {
                return ResourceManager.GetString("MainWindow_Registrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求信息 的本地化字符串。
        /// </summary>
        public static string MainWindow_RequestInfo {
            get {
                return ResourceManager.GetString("MainWindow_RequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string MainWindow_Reset {
            get {
                return ResourceManager.GetString("MainWindow_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示所有通话 的本地化字符串。
        /// </summary>
        public static string MainWindow_ShowCalls {
            get {
                return ResourceManager.GetString("MainWindow_ShowCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示文件传输记录 的本地化字符串。
        /// </summary>
        public static string MainWindow_ShowFileTransfers {
            get {
                return ResourceManager.GetString("MainWindow_ShowFileTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示历史通话 的本地化字符串。
        /// </summary>
        public static string MainWindow_ShowHistory {
            get {
                return ResourceManager.GetString("MainWindow_ShowHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示及时消息记录 的本地化字符串。
        /// </summary>
        public static string MainWindow_ShowMessages {
            get {
                return ResourceManager.GetString("MainWindow_ShowMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string MainWindow_SignIn {
            get {
                return ResourceManager.GetString("MainWindow_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        public static string MainWindow_SignOut {
            get {
                return ResourceManager.GetString("MainWindow_SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小精灵网络电话 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string TabAbout {
            get {
                return ResourceManager.GetString("TabAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份验证 的本地化字符串。
        /// </summary>
        public static string TabAuthentication {
            get {
                return ResourceManager.GetString("TabAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拨号 的本地化字符串。
        /// </summary>
        public static string TabCall {
            get {
                return ResourceManager.GetString("TabCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码方式 的本地化字符串。
        /// </summary>
        public static string TabCodecs {
            get {
                return ResourceManager.GetString("TabCodecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯录 的本地化字符串。
        /// </summary>
        public static string TabContacts {
            get {
                return ResourceManager.GetString("TabContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网址*: 的本地化字符串。
        /// </summary>
        public static string TabContacts_BaseURI {
            get {
                return ResourceManager.GetString("TabContacts_BaseURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码: 的本地化字符串。
        /// </summary>
        public static string TabContacts_Password {
            get {
                return ResourceManager.GetString("TabContacts_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地存储 的本地化字符串。
        /// </summary>
        public static string TabContacts_StorageLocal {
            get {
                return ResourceManager.GetString("TabContacts_StorageLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 远程存储 的本地化字符串。
        /// </summary>
        public static string TabContacts_StorageRemote {
            get {
                return ResourceManager.GetString("TabContacts_StorageRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时: 的本地化字符串。
        /// </summary>
        public static string TabContacts_Timeout {
            get {
                return ResourceManager.GetString("TabContacts_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语音电话 的本地化字符串。
        /// </summary>
        public static string TabContacts_ToolTipMakeVideoCall {
            get {
                return ResourceManager.GetString("TabContacts_ToolTipMakeVideoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频电话 的本地化字符串。
        /// </summary>
        public static string TabContacts_ToolTipMakeVoiceCall {
            get {
                return ResourceManager.GetString("TabContacts_ToolTipMakeVoiceCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送文件 的本地化字符串。
        /// </summary>
        public static string TabContacts_ToolTipSendFile {
            get {
                return ResourceManager.GetString("TabContacts_ToolTipSendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送及时消息 的本地化字符串。
        /// </summary>
        public static string TabContacts_ToolTipStartChat {
            get {
                return ResourceManager.GetString("TabContacts_ToolTipStartChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名*: 的本地化字符串。
        /// </summary>
        public static string TabContacts_Username {
            get {
                return ResourceManager.GetString("TabContacts_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XCAP Preferences 的本地化字符串。
        /// </summary>
        public static string TabContacts_XCAPPrefs {
            get {
                return ResourceManager.GetString("TabContacts_XCAPPrefs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string TabGeneral {
            get {
                return ResourceManager.GetString("TabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ENUM (E.164) domain 的本地化字符串。
        /// </summary>
        public static string TabGeneral_Enum {
            get {
                return ResourceManager.GetString("TabGeneral_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Launch when system starts 的本地化字符串。
        /// </summary>
        public static string TabGeneral_LaunchWhenStart {
            get {
                return ResourceManager.GetString("TabGeneral_LaunchWhenStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media Profile 的本地化字符串。
        /// </summary>
        public static string TabGeneral_Profile {
            get {
                return ResourceManager.GetString("TabGeneral_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通话记录 的本地化字符串。
        /// </summary>
        public static string TabHistory {
            get {
                return ResourceManager.GetString("TabHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户配置 的本地化字符串。
        /// </summary>
        public static string TabIdentity {
            get {
                return ResourceManager.GetString("TabIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AMF*: 的本地化字符串。
        /// </summary>
        public static string TabIdentity_AMF {
            get {
                return ResourceManager.GetString("TabIdentity_AMF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接字符串 的本地化字符串。
        /// </summary>
        public static string TabIdentity_ConSettings {
            get {
                return ResourceManager.GetString("TabIdentity_ConSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称*: 的本地化字符串。
        /// </summary>
        public static string TabIdentity_DisplayName {
            get {
                return ResourceManager.GetString("TabIdentity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用早期 3GPP IMS 安全策略 的本地化字符串。
        /// </summary>
        public static string TabIdentity_EnableEarlyIMS {
            get {
                return ResourceManager.GetString("TabIdentity_EnableEarlyIMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户ID*: 的本地化字符串。
        /// </summary>
        public static string TabIdentity_OpId {
            get {
                return ResourceManager.GetString("TabIdentity_OpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码*: 的本地化字符串。
        /// </summary>
        public static string TabIdentity_Password {
            get {
                return ResourceManager.GetString("TabIdentity_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私有的: 的本地化字符串。
        /// </summary>
        public static string TabIdentity_Privacy {
            get {
                return ResourceManager.GetString("TabIdentity_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 私有配置*: 的本地化字符串。
        /// </summary>
        public static string TabIdentity_PrivateId {
            get {
                return ResourceManager.GetString("TabIdentity_PrivateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共配置*: 的本地化字符串。
        /// </summary>
        public static string TabIdentity_PublicId {
            get {
                return ResourceManager.GetString("TabIdentity_PublicId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 范围*: 的本地化字符串。
        /// </summary>
        public static string TabIdentity_Realm {
            get {
                return ResourceManager.GetString("TabIdentity_Realm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全级别 的本地化字符串。
        /// </summary>
        public static string TabIdentity_Security {
            get {
                return ResourceManager.GetString("TabIdentity_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        public static string TabMessaging {
            get {
                return ResourceManager.GetString("TabMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binary Encoding (3GPP SMSIP) 的本地化字符串。
        /// </summary>
        public static string TabMessaging_Binary {
            get {
                return ResourceManager.GetString("TabMessaging_Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聊天 的本地化字符串。
        /// </summary>
        public static string TabMessaging_Chat {
            get {
                return ResourceManager.GetString("TabMessaging_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Instant Message Disposition Notification (IMDN) 的本地化字符串。
        /// </summary>
        public static string TabMessaging_EnableIMDN {
            get {
                return ResourceManager.GetString("TabMessaging_EnableIMDN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Indication of Message Composition for Instant Messaging 的本地化字符串。
        /// </summary>
        public static string TabMessaging_EnableIsComposing {
            get {
                return ResourceManager.GetString("TabMessaging_EnableIsComposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable MSRP Failure Reports 的本地化字符串。
        /// </summary>
        public static string TabMessaging_EnableMSRPFailureReports {
            get {
                return ResourceManager.GetString("TabMessaging_EnableMSRPFailureReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable MSRP Success Reports 的本地化字符串。
        /// </summary>
        public static string TabMessaging_EnableMSRPSuccessReports {
            get {
                return ResourceManager.GetString("TabMessaging_EnableMSRPSuccessReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable OMA Final Delivery Reports 的本地化字符串。
        /// </summary>
        public static string TabMessaging_EnableOMAFinalDeliveryReports {
            get {
                return ResourceManager.GetString("TabMessaging_EnableOMAFinalDeliveryReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plain Text Encoding 的本地化字符串。
        /// </summary>
        public static string TabMessaging_PlainText {
            get {
                return ResourceManager.GetString("TabMessaging_PlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短信息 的本地化字符串。
        /// </summary>
        public static string TabMessaging_SMS {
            get {
                return ResourceManager.GetString("TabMessaging_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 短信息中心 的本地化字符串。
        /// </summary>
        public static string TabMessaging_SMSC {
            get {
                return ResourceManager.GetString("TabMessaging_SMSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NATT 的本地化字符串。
        /// </summary>
        public static string TabNATT {
            get {
                return ResourceManager.GetString("TabNATT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Discover STUN/TURN server 的本地化字符串。
        /// </summary>
        public static string TabNATT_Discover_STUNSrv {
            get {
                return ResourceManager.GetString("TabNATT_Discover_STUNSrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable STUN or TURN 的本地化字符串。
        /// </summary>
        public static string TabNATT_EnableSTUN {
            get {
                return ResourceManager.GetString("TabNATT_EnableSTUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port: 的本地化字符串。
        /// </summary>
        public static string TabNATT_Port {
            get {
                return ResourceManager.GetString("TabNATT_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server: 的本地化字符串。
        /// </summary>
        public static string TabNATT_Server {
            get {
                return ResourceManager.GetString("TabNATT_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STUN / TURN 的本地化字符串。
        /// </summary>
        public static string TabNATT_STUNTURN {
            get {
                return ResourceManager.GetString("TabNATT_STUNTURN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NAT Traversal 的本地化字符串。
        /// </summary>
        public static string TabNATT_Title {
            get {
                return ResourceManager.GetString("TabNATT_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use this STUN/TURN server 的本地化字符串。
        /// </summary>
        public static string TabNATT_UseSTUNSrv {
            get {
                return ResourceManager.GetString("TabNATT_UseSTUNSrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network 的本地化字符串。
        /// </summary>
        public static string TabNetwork {
            get {
                return ResourceManager.GetString("TabNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Access Type 的本地化字符串。
        /// </summary>
        public static string TabNetwork_AccessType {
            get {
                return ResourceManager.GetString("TabNetwork_AccessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy-CSCF discovery using DHCP 的本地化字符串。
        /// </summary>
        public static string TabNetwork_DiscoDHCP {
            get {
                return ResourceManager.GetString("TabNetwork_DiscoDHCP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy-CSCF discovery using DNS NAPTR + SRV 的本地化字符串。
        /// </summary>
        public static string TabNetwork_DiscoDNS {
            get {
                return ResourceManager.GetString("TabNetwork_DiscoDNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Signaling Compression (SigComp) 的本地化字符串。
        /// </summary>
        public static string TabNetwork_EnableSigComp {
            get {
                return ResourceManager.GetString("TabNetwork_EnableSigComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info: 的本地化字符串。
        /// </summary>
        public static string TabNetwork_Info {
            get {
                return ResourceManager.GetString("TabNetwork_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP Version 的本地化字符串。
        /// </summary>
        public static string TabNetwork_IPVersion {
            get {
                return ResourceManager.GetString("TabNetwork_IPVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network 的本地化字符串。
        /// </summary>
        public static string TabNetwork_Network {
            get {
                return ResourceManager.GetString("TabNetwork_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy-CSCF Host*: 的本地化字符串。
        /// </summary>
        public static string TabNetwork_ProxyHost {
            get {
                return ResourceManager.GetString("TabNetwork_ProxyHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proxy-CSCF port*: 的本地化字符串。
        /// </summary>
        public static string TabNetwork_ProxyPort {
            get {
                return ResourceManager.GetString("TabNetwork_ProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string TabNetwork_Settings {
            get {
                return ResourceManager.GetString("TabNetwork_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Networking 的本地化字符串。
        /// </summary>
        public static string TabNetwork_Title {
            get {
                return ResourceManager.GetString("TabNetwork_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transport*: 的本地化字符串。
        /// </summary>
        public static string TabNetwork_Transport {
            get {
                return ResourceManager.GetString("TabNetwork_Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人中心 的本地化字符串。
        /// </summary>
        public static string TabPersonalCenter {
            get {
                return ResourceManager.GetString("TabPersonalCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Presence 的本地化字符串。
        /// </summary>
        public static string TabPresence {
            get {
                return ResourceManager.GetString("TabPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avatar Size MUST be at least 80x60 or 60x80 and ratio must be 4/3 的本地化字符串。
        /// </summary>
        public static string TabPresence_AvatarSize {
            get {
                return ResourceManager.GetString("TabPresence_AvatarSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Publication 的本地化字符串。
        /// </summary>
        public static string TabPresence_EnablePublication {
            get {
                return ResourceManager.GetString("TabPresence_EnablePublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable RLS when XCAP is enabled 的本地化字符串。
        /// </summary>
        public static string TabPresence_EnableRLS {
            get {
                return ResourceManager.GetString("TabPresence_EnableRLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Subscription 的本地化字符串。
        /// </summary>
        public static string TabPresence_EnableSubscription {
            get {
                return ResourceManager.GetString("TabPresence_EnableSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Free Text 的本地化字符串。
        /// </summary>
        public static string TabPresence_FreeText {
            get {
                return ResourceManager.GetString("TabPresence_FreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home Page 的本地化字符串。
        /// </summary>
        public static string TabPresence_HomePage {
            get {
                return ResourceManager.GetString("TabPresence_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hyper-Availability Timeout 的本地化字符串。
        /// </summary>
        public static string TabPresence_HyperAvailTimeout {
            get {
                return ResourceManager.GetString("TabPresence_HyperAvailTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minutes 的本地化字符串。
        /// </summary>
        public static string TabPresence_Minutes {
            get {
                return ResourceManager.GetString("TabPresence_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publication 的本地化字符串。
        /// </summary>
        public static string TabPresence_Publication {
            get {
                return ResourceManager.GetString("TabPresence_Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status Icon (Click on the box to change) 的本地化字符串。
        /// </summary>
        public static string TabPresence_StatusIcon {
            get {
                return ResourceManager.GetString("TabPresence_StatusIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscription 的本地化字符串。
        /// </summary>
        public static string TabPresence_Subscription {
            get {
                return ResourceManager.GetString("TabPresence_Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QoS/QoE 的本地化字符串。
        /// </summary>
        public static string TabQoS {
            get {
                return ResourceManager.GetString("TabQoS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bandwidth: 的本地化字符串。
        /// </summary>
        public static string TabQoS_Bandwidth {
            get {
                return ResourceManager.GetString("TabQoS_Bandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Session Timers 的本地化字符串。
        /// </summary>
        public static string TabQoS_EnableSessionTimers {
            get {
                return ResourceManager.GetString("TabQoS_EnableSessionTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string TabQoS_General {
            get {
                return ResourceManager.GetString("TabQoS_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preconditions 的本地化字符串。
        /// </summary>
        public static string TabQoS_Preconditions {
            get {
                return ResourceManager.GetString("TabQoS_Preconditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferred video Size: 的本地化字符串。
        /// </summary>
        public static string TabQoS_PrefVideoSize {
            get {
                return ResourceManager.GetString("TabQoS_PrefVideoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresher: 的本地化字符串。
        /// </summary>
        public static string TabQoS_Refresher {
            get {
                return ResourceManager.GetString("TabQoS_Refresher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Session Timers 的本地化字符串。
        /// </summary>
        public static string TabQoS_SessionTimers {
            get {
                return ResourceManager.GetString("TabQoS_SessionTimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strength: 的本地化字符串。
        /// </summary>
        public static string TabQoS_Strength {
            get {
                return ResourceManager.GetString("TabQoS_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timeout: 的本地化字符串。
        /// </summary>
        public static string TabQoS_Timeout {
            get {
                return ResourceManager.GetString("TabQoS_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QoS/QoE 的本地化字符串。
        /// </summary>
        public static string TabQoS_Title {
            get {
                return ResourceManager.GetString("TabQoS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type: 的本地化字符串。
        /// </summary>
        public static string TabQoS_Type {
            get {
                return ResourceManager.GetString("TabQoS_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security 的本地化字符串。
        /// </summary>
        public static string TabSecurity {
            get {
                return ResourceManager.GetString("TabSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Algorithm: 的本地化字符串。
        /// </summary>
        public static string TabSecurity_Algorithm {
            get {
                return ResourceManager.GetString("TabSecurity_Algorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Certificate File: 的本地化字符串。
        /// </summary>
        public static string TabSecurity_CertFile {
            get {
                return ResourceManager.GetString("TabSecurity_CertFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Encrypt Algorithm: 的本地化字符串。
        /// </summary>
        public static string TabSecurity_EAlgorithm {
            get {
                return ResourceManager.GetString("TabSecurity_EAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable IPSec 的本地化字符串。
        /// </summary>
        public static string TabSecurity_EnableIPSec {
            get {
                return ResourceManager.GetString("TabSecurity_EnableIPSec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IPSec Parameters 的本地化字符串。
        /// </summary>
        public static string TabSecurity_IPSecParams {
            get {
                return ResourceManager.GetString("TabSecurity_IPSecParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mode: 的本地化字符串。
        /// </summary>
        public static string TabSecurity_Mode {
            get {
                return ResourceManager.GetString("TabSecurity_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Private File: 的本地化字符串。
        /// </summary>
        public static string TabSecurity_PrivateFile {
            get {
                return ResourceManager.GetString("TabSecurity_PrivateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Protocol: 的本地化字符串。
        /// </summary>
        public static string TabSecurity_Protocol {
            get {
                return ResourceManager.GetString("TabSecurity_Protocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Public File 的本地化字符串。
        /// </summary>
        public static string TabSecurity_PublicFile {
            get {
                return ResourceManager.GetString("TabSecurity_PublicFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SRTP Parameters 的本地化字符串。
        /// </summary>
        public static string TabSecurity_SRTPParams {
            get {
                return ResourceManager.GetString("TabSecurity_SRTPParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TLS Parameters 的本地化字符串。
        /// </summary>
        public static string TabSecurity_TLSParams {
            get {
                return ResourceManager.GetString("TabSecurity_TLSParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Accepted 的本地化字符串。
        /// </summary>
        public static string Text_Accepted {
            get {
                return ResourceManager.GetString("Text_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加联系人 的本地化字符串。
        /// </summary>
        public static string Text_AddContact {
            get {
                return ResourceManager.GetString("Text_AddContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应答 的本地化字符串。
        /// </summary>
        public static string Text_Answer {
            get {
                return ResourceManager.GetString("Text_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼叫 的本地化字符串。
        /// </summary>
        public static string Text_Call {
            get {
                return ResourceManager.GetString("Text_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理呼叫 的本地化字符串。
        /// </summary>
        public static string Text_CallInProgress {
            get {
                return ResourceManager.GetString("Text_CallInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保持通话 的本地化字符串。
        /// </summary>
        public static string Text_CallPlacedOnHold {
            get {
                return ResourceManager.GetString("Text_CallPlacedOnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消保持 的本地化字符串。
        /// </summary>
        public static string Text_CallTakenOffHold {
            get {
                return ResourceManager.GetString("Text_CallTakenOffHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呼叫结束 的本地化字符串。
        /// </summary>
        public static string Text_CallTerminated {
            get {
                return ResourceManager.GetString("Text_CallTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Call Transfer 的本地化字符串。
        /// </summary>
        public static string Text_CallTransfer {
            get {
                return ResourceManager.GetString("Text_CallTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Text_Cancel {
            get {
                return ResourceManager.GetString("Text_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Completed 的本地化字符串。
        /// </summary>
        public static string Text_Completed {
            get {
                return ResourceManager.GetString("Text_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在呼叫 的本地化字符串。
        /// </summary>
        public static string Text_EarlyMediaStarted {
            get {
                return ResourceManager.GetString("Text_EarlyMediaStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑联系人 的本地化字符串。
        /// </summary>
        public static string Text_EditContact {
            get {
                return ResourceManager.GetString("Text_EditContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string Text_Failed {
            get {
                return ResourceManager.GetString("Text_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to place remote party on hold 的本地化字符串。
        /// </summary>
        public static string Text_FailedToPlaceRemotePartyOnHold {
            get {
                return ResourceManager.GetString("Text_FailedToPlaceRemotePartyOnHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to unhold call 的本地化字符串。
        /// </summary>
        public static string Text_FailedToUnholdCall {
            get {
                return ResourceManager.GetString("Text_FailedToUnholdCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保持通话 的本地化字符串。
        /// </summary>
        public static string Text_HoldCall {
            get {
                return ResourceManager.GetString("Text_HoldCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在通话 的本地化字符串。
        /// </summary>
        public static string Text_InCall {
            get {
                return ResourceManager.GetString("Text_InCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主叫号码 的本地化字符串。
        /// </summary>
        public static string Text_IncomingCall {
            get {
                return ResourceManager.GetString("Text_IncomingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Initiated 的本地化字符串。
        /// </summary>
        public static string Text_Initiated {
            get {
                return ResourceManager.GetString("Text_Initiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placed on hold by remote party 的本地化字符串。
        /// </summary>
        public static string Text_PlacedOnHoldByRemoteParty {
            get {
                return ResourceManager.GetString("Text_PlacedOnHoldByRemoteParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续通话 的本地化字符串。
        /// </summary>
        public static string Text_ResumeCall {
            get {
                return ResourceManager.GetString("Text_ResumeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对方正在振铃.... 的本地化字符串。
        /// </summary>
        public static string Text_Ringing {
            get {
                return ResourceManager.GetString("Text_Ringing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送短消息 的本地化字符串。
        /// </summary>
        public static string Text_SendSMS {
            get {
                return ResourceManager.GetString("Text_SendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送文本 的本地化字符串。
        /// </summary>
        public static string Text_SendText {
            get {
                return ResourceManager.GetString("Text_SendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Taken off hold by remote party 的本地化字符串。
        /// </summary>
        public static string Text_TakenOffHoldByRemoteParty {
            get {
                return ResourceManager.GetString("Text_TakenOffHoldByRemoteParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在呼叫 的本地化字符串。
        /// </summary>
        public static string Text_TalkingWith {
            get {
                return ResourceManager.GetString("Text_TalkingWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer 的本地化字符串。
        /// </summary>
        public static string Text_Transfer {
            get {
                return ResourceManager.GetString("Text_Transfer", resourceCulture);
            }
        }
    }
}
