//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BogheApp.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BogheApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap avatar_48 {
            get {
                object obj = ResourceManager.GetObject("avatar_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bullet_ball_glass_blue_16 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_blue_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bullet_ball_glass_blue_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_blue_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bullet_ball_glass_green_16 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_green_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bullet_ball_glass_green_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_green_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bullet_ball_glass_grey_16 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_grey_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bullet_ball_glass_grey_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_grey_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bullet_ball_glass_red_16 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_red_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bullet_ball_glass_red_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_red_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bullet_ball_glass_yellow_16 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_yellow_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap bullet_ball_glass_yellow_24 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_glass_yellow_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap call_hold_16 {
            get {
                object obj = ResourceManager.GetObject("call_hold_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap call_incoming_45 {
            get {
                object obj = ResourceManager.GetObject("call_incoming_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap call_missed_45 {
            get {
                object obj = ResourceManager.GetObject("call_missed_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap call_outgoing_45 {
            get {
                object obj = ResourceManager.GetObject("call_outgoing_45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap call_resume_16 {
            get {
                object obj = ResourceManager.GetObject("call_resume_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream connevent {
            get {
                return ResourceManager.GetStream("connevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream connevent1 {
            get {
                return ResourceManager.GetStream("connevent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap document_down_16 {
            get {
                object obj = ResourceManager.GetObject("document_down_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap document_down_32 {
            get {
                object obj = ResourceManager.GetObject("document_down_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap document_forbidden_16 {
            get {
                object obj = ResourceManager.GetObject("document_forbidden_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap document_forbidden_32 {
            get {
                object obj = ResourceManager.GetObject("document_forbidden_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap document_up_16 {
            get {
                object obj = ResourceManager.GetObject("document_up_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap document_up_32 {
            get {
                object obj = ResourceManager.GetObject("document_up_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_0 {
            get {
                return ResourceManager.GetStream("dtmf_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_01 {
            get {
                return ResourceManager.GetStream("dtmf_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_1 {
            get {
                return ResourceManager.GetStream("dtmf_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_11 {
            get {
                return ResourceManager.GetStream("dtmf_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_2 {
            get {
                return ResourceManager.GetStream("dtmf_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_21 {
            get {
                return ResourceManager.GetStream("dtmf_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_3 {
            get {
                return ResourceManager.GetStream("dtmf_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_31 {
            get {
                return ResourceManager.GetStream("dtmf_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_4 {
            get {
                return ResourceManager.GetStream("dtmf_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_41 {
            get {
                return ResourceManager.GetStream("dtmf_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_5 {
            get {
                return ResourceManager.GetStream("dtmf_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_51 {
            get {
                return ResourceManager.GetStream("dtmf_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_6 {
            get {
                return ResourceManager.GetStream("dtmf_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_61 {
            get {
                return ResourceManager.GetStream("dtmf_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_7 {
            get {
                return ResourceManager.GetStream("dtmf_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_71 {
            get {
                return ResourceManager.GetStream("dtmf_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_8 {
            get {
                return ResourceManager.GetStream("dtmf_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_81 {
            get {
                return ResourceManager.GetStream("dtmf_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_9 {
            get {
                return ResourceManager.GetStream("dtmf_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_91 {
            get {
                return ResourceManager.GetStream("dtmf_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_pound {
            get {
                return ResourceManager.GetStream("dtmf_pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_pound1 {
            get {
                return ResourceManager.GetStream("dtmf_pound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_star {
            get {
                return ResourceManager.GetStream("dtmf_star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream dtmf_star1 {
            get {
                return ResourceManager.GetStream("dtmf_star1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap hourglass_24 {
            get {
                object obj = ResourceManager.GetObject("hourglass_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap icon_16 {
            get {
                object obj = ResourceManager.GetObject("icon_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon icon_message_16 {
            get {
                object obj = ResourceManager.GetObject("icon_message_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Icon icon_messages_16 {
            get {
                object obj = ResourceManager.GetObject("icon_messages_16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap key_ok_24 {
            get {
                object obj = ResourceManager.GetObject("key_ok_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap keybroad {
            get {
                object obj = ResourceManager.GetObject("keybroad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap lock_error_16 {
            get {
                object obj = ResourceManager.GetObject("lock_error_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap lock_error_24 {
            get {
                object obj = ResourceManager.GetObject("lock_error_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap lock_error_32 {
            get {
                object obj = ResourceManager.GetObject("lock_error_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap lock_ok_16 {
            get {
                object obj = ResourceManager.GetObject("lock_ok_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap lock_ok_24 {
            get {
                object obj = ResourceManager.GetObject("lock_ok_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap lock_ok_32 {
            get {
                object obj = ResourceManager.GetObject("lock_ok_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap lock_open_24 {
            get {
                object obj = ResourceManager.GetObject("lock_open_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap lock_warning_16 {
            get {
                object obj = ResourceManager.GetObject("lock_warning_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap lock_warning_24 {
            get {
                object obj = ResourceManager.GetObject("lock_warning_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap lock_warning_32 {
            get {
                object obj = ResourceManager.GetObject("lock_warning_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;log4net&gt;
        ///  
        ///  &lt;appender name=&quot;ConsoleAppender&quot; type=&quot;log4net.Appender.ConsoleAppender&quot;&gt;
        ///    &lt;layout type=&quot;log4net.Layout.PatternLayout&quot;&gt;
        ///      &lt;conversionPattern value=&quot;%date %-5level [%thread] %logger:%line - %message%newline&quot;/&gt;
        ///    &lt;/layout&gt;
        ///  &lt;/appender&gt;
        ///
        ///  &lt;appender name=&quot;FileAppender&quot; type=&quot;log4net.Appender.RollingFileAppender&quot;&gt;
        ///    &lt;file value=&quot;{0}\Boghe.log&quot;/&gt;
        ///    &lt;appendToFile value=&quot;true&quot;/&gt;
        ///    &lt;rollingStyle value=&quot;Date&quot;/&gt;
        ///    &lt;datePattern value [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string log4net_xml {
            get {
                return ResourceManager.GetString("log4net_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap message_16 {
            get {
                object obj = ResourceManager.GetObject("message_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap message_24 {
            get {
                object obj = ResourceManager.GetObject("message_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap messages_16 {
            get {
                object obj = ResourceManager.GetObject("messages_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap messages_24 {
            get {
                object obj = ResourceManager.GetObject("messages_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap messages_32 {
            get {
                object obj = ResourceManager.GetObject("messages_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream newsms {
            get {
                return ResourceManager.GetStream("newsms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream newsms1 {
            get {
                return ResourceManager.GetStream("newsms1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap phone_hang_up_32 {
            get {
                object obj = ResourceManager.GetObject("phone_hang_up_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap phone_pick_up_32 {
            get {
                object obj = ResourceManager.GetObject("phone_pick_up_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ringbacktone {
            get {
                return ResourceManager.GetStream("ringbacktone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ringbacktone1 {
            get {
                return ResourceManager.GetStream("ringbacktone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ringtone {
            get {
                return ResourceManager.GetStream("ringtone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        public static System.IO.UnmanagedMemoryStream ringtone1 {
            get {
                return ResourceManager.GetStream("ringtone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap secure_16 {
            get {
                object obj = ResourceManager.GetObject("secure_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap signin_16 {
            get {
                object obj = ResourceManager.GetObject("signin_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap signin_161 {
            get {
                object obj = ResourceManager.GetObject("signin_161", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap signout_16 {
            get {
                object obj = ResourceManager.GetObject("signout_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap sound_off_16 {
            get {
                object obj = ResourceManager.GetObject("sound_off_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap sound_off_32 {
            get {
                object obj = ResourceManager.GetObject("sound_off_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap sound_on_16 {
            get {
                object obj = ResourceManager.GetObject("sound_on_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap sound_on_32 {
            get {
                object obj = ResourceManager.GetObject("sound_on_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Strings {
            get {
                return ResourceManager.GetString("Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string Strings_fr_FR {
            get {
                return ResourceManager.GetString("Strings_fr_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap user_16 {
            get {
                object obj = ResourceManager.GetObject("user_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap user_back16 {
            get {
                object obj = ResourceManager.GetObject("user_back16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap user_busy_16 {
            get {
                object obj = ResourceManager.GetObject("user_busy_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap user_hyper_avail_16 {
            get {
                object obj = ResourceManager.GetObject("user_hyper_avail_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap user_mobilephone_32 {
            get {
                object obj = ResourceManager.GetObject("user_mobilephone_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap user_offline_16 {
            get {
                object obj = ResourceManager.GetObject("user_offline_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap user_onthephone_16 {
            get {
                object obj = ResourceManager.GetObject("user_onthephone_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap user_time_16 {
            get {
                object obj = ResourceManager.GetObject("user_time_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap video_pause_16 {
            get {
                object obj = ResourceManager.GetObject("video_pause_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap video_play_16 {
            get {
                object obj = ResourceManager.GetObject("video_play_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap 键盘 {
            get {
                object obj = ResourceManager.GetObject("键盘", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
